stages: 
- stage: stageA
  displayName: Stage A
  jobs: 
    - job: jobA1
      displayName: Job A 1
      pool: 
        vmImage: 'windows-latest'
    - job: jobA2
      displayName: Job A 2
      pool: 
        vmImage: 'windows-latest'

- stage: stageB
  displayName: Stage B
  dependsOn: stageA
  jobs: 
    - job: jobB1
      displayName: Job B 1
      pool: 
        vmImage: 'windows-latest'
    - job: jobB2
      displayName: Job B 2
      pool: 
        vmImage: 'windows-latest'
- stage: stageC
  displayName: Stage C
  dependsOn: stageB
  jobs: 
    - job: jobC1
      displayName: Job C 1
      pool: 
        vmImage: 'windows-latest'
    - job: jobC2
      displayName: Job C 2
      pool: 
        vmImage: 'windows-latest'
- stage: stageD
  displayName: Stage D
  dependsOn: stageB
  jobs: 
    - job: jobD1
      displayName: Job D 1
      pool: 
        vmImage: 'windows-latest'
    - job: jobD2
      displayName: Job D 2
      pool: 
        vmImage: 'windows-latest'