jobs: 
- job: job1
  pool: 
    vmImage: ubuntu-latest
  steps: 
  - template: step1.yml

- job: job2
  pool: 
    vmImage: ubuntu-latest
  steps: 
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1 (5762a227-f807-4aed-8497-0a532cf55cb5)'
      appType: 'webApp'
      WebAppName: 'busprime'
      packageForLinux: '.'